server:
  port: 8004
spring:
  application:
    name: service-vod
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
aliyun-accessKeyId: ************************************
aliyun-accessKeySecret: ************************************
