server:
  port: 8002
spring:
  application:
    name: service-oos

  profiles:
    active: dev

#配置阿里云oos配置
aliyun-file-endpoint: oss-cn-hangzhou.aliyuncs.com
aliyun-file-accessKeyId: LTAI4GDVJBAGbNKzuB4zK1dT
aliyun-file-accessKeySecret: XV6oreiX5mjgw508ChRsjQq6qguhW6

aliyun-file-bucketName: zzd-guli-edu