server:
  port: 8006
spring:
  application:
    name: service-msm
  redis:
    host: 121.199.9.8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///guli_college?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: zuda123